### ISSUE TITLE
KeyMagic-v2.0.1.0.exe is flagged dangerous and blocked by Chrome.

### ISSUE THREAD

**Issue by mhzaw** [thantthet/keymagic#104]
![image](https://user-images.githubusercontent.com/41136266/93853894-b8b28a00-fcda-11ea-8b76-8b7508297e67.png)

**Comment by GitSheru** [comment]
![IMG_20201011_194241_110](https://user-images.githubusercontent.com/58210837/95684427-5c1bfe00-0bfa-11eb-8801-08430f145355.jpg)
5 different AV engines detected it as malicious.

**Comment by landlight** [comment]
having the same problem!
