### ISSUE TITLE
KEditor does not recognize Unicode character codes for Gothic language (not even the newer version)

### ISSUE THREAD

**Issue by klanvloar** [thantthet/keymagic#106]
What to do? Help please (windows 10 user).  
https://www.unicode.org/charts/PDF/U10330.pdf
![GOTI](https://user-images.githubusercontent.com/72545388/95430374-50d28500-0911-11eb-992d-67735eafdb8b.png)

Is there any solution? Wikipedia says:

_The Gothic alphabet was added to the Unicode Standard in March 2001 with the release of version 3.1.

The Unicode block for Gothic is U+10330– U+1034F in the Supplementary Multilingual Plane. As older software that uses UCS-2 (the predecessor of UTF-16) assumes that all Unicode codepoints can be expressed as 16 bit numbers (U+FFFF or lower, the Basic Multilingual Plane), problems may be encountered using the Gothic alphabet Unicode range and others outside of the Basic Multilingual Plane._

**Comment by klanvloar** [comment]
Is there any solution? Wikipedia says:

_The Gothic alphabet was added to the Unicode Standard in March 2001 with the release of version 3.1.

The Unicode block for Gothic is U+10330– U+1034F in the Supplementary Multilingual Plane. As older software that uses UCS-2 (the predecessor of UTF-16) assumes that all Unicode codepoints can be expressed as 16 bit numbers (U+FFFF or lower, the Basic Multilingual Plane), problems may be encountered using the Gothic alphabet Unicode range and others outside of the Basic Multilingual Plane._

**Comment by thantthet** [comment]
You are right. KeyMagic currently doesn't support for unicode character beyond U+FFFF. I'll try to fix this issue in the future.
