### ISSUE TITLE
Keymap request 

### ISSUE THREAD

**Issue by AungMyoKo** [thantthet/keymagic#112]
Japanese keymap လေး request လုပ်ချင်တာပါ အဆင်ပြေမယ် ဆို ဖန်တီးပေးပါဦး

**Comment by kokoye2007** [comment]
Japan က ကီးဘုတ်တွေ ရှိပြီးသားပါ
ဘယ်လို Request လုပ်ချင်တာလဲ ပေါ်မူတည်ပါတယ်

1) Hiragana 
2) Katakana 
3) Kanji
4) Romaji 

ဘယ်အပေါ်မှာ အခြေခံတဲ့ ဘယ်လက်ကွက်ပေါ်အခြေခံတဲ့ ကီးဘုတ်လဲ သိဖို့လိုပါတယ်

**Comment by AungMyoKo** [comment]
hiragana နဲ့ kanji ဗျ အဆင်ပြေရင် request လုက်ချင်ပါတယ်

**Comment by kokoye2007** [comment]
- အဲ့တာတွေက Windows / Linux / Mac အကုန် Native Keyboard တွေ ရှိပြီးသားထင်ပါတယ်။
Hiragana နဲ့ Katakana က လွယ်ပြီး Kanji အတွက်ဆို Dictionary ပါလိုမယ်ဗျ.

**Comment by AungMyoKo** [comment]
ဟုတ်ကဲ့ ကျေးဇူးတင်ပါတယ်ဗျ
