### ISSUE TITLE
personal package archive(ppa) doesn't work in ubuntu

### ISSUE THREAD

**Issue by minzawthein** [thantthet/keymagic#115]
**Describe the bug (ပြဿနာကိုရေးပါ)**
A clear and concise description of what the bug is. (ဘာဖြစ်တယ်ဆိုတာကို ရှင်းရှင်းလင်းလင်းရေးပေးပါ။)

**To Reproduce (ဘာလုပ်ရင်ဖြစ်တာလဲ)**
Steps to reproduce the behavior: (အောက်ပါအဆင့်များအတိုင်း လုပ်ရင်ဖြစ်ပါတယ် -)

**Expected behavior (ဖြစ်သင့်သော အခြေအနေ**)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kokoye2007** [comment]
တချို့ဗားရှင်းတွေအတွက် PPA မတင်ပေးဖြစ်သေးတာပါ။
သွင်းပြီးမှ အဆင်မပြေတဲ့ Version လေး ရေးပေးခဲ့ပါ။
deb ဖိုင်ကို ဆွဲပြီး သွင်းလို့တော့ ရပါလိမ့်မယ်။
