### ISSUE TITLE
Keymagic back key stuck error

### ISSUE THREAD

**Issue by ArYao27** [thantthet/keymagic#120]
​ ​Back key ကပ်နေတဲ့  error ပါ

မြန်မာစာ ရိုက်ပြီး နောက်ပြန်ဆုတ်တာ ဖျက်တာလုပ်ချင်လို့ ​back key နှိပ်တဲ့အခါမှာ အနည်းဆုံး ၂ချက်နှိပ်မှ တစ်ခါအလုပ်လုပ်ပါတယ် တစ်ခါတစ်လေ ၃ ၄ချက်လောက်ထိ key ကပ်နေတတ်ပါတယ်

ပထမတစ်ကြိမ်က windows 10 မှာ ကြုံလိုက်တာပါ Keymagic version ကြောင့်ထင်လို့ အသစ်ပြန်ဒေါင်းပြီး စမ်းကြည့်လည်း မရတာနဲ့ windows ကြောင့်ဆိုပြီး windows အသစ်ပြန်တင်လိုက်တာ အဆင်ပြေသွားပါတယ်
အခုဒုတိယအကြိမ်ကတော့ အသိမိတ်ဆွေတစ်ဦးရဲ့ Macbook macOS Big Sur 11.6 မှာ အပေါ်က error နည်းတူ ကြုံနေရတာပါ

(မှတ်ချက်။ ကျွန်တော့်မှာရှိတဲ့ macOS Big Sur 11.6 နဲ့ Macbook မှာတော့ အဲ့ဒီ error မတွေ့ရဘူးဗျ)

**Comment by thantthet** [comment]
ဘာကီးဘုတ်သုံးတာလဲဗျ ဘာစာရိုက်ရိုက်ဖြစ်တာလား
