### ISSUE TITLE
KeyMagic Report

### ISSUE THREAD

**Issue by zawjl** [thantthet/keymagic#121]
**Can't add back font or keyboard**

> fonts တွေကို မတော် တဆ ဖျက်လိုက် မိတာ uninstall ပြီးတော့ install ပြန်လုပ်လည်း မ မြင်ရတော့ လို့
**ဘာလုပ်ရင်ဖြစ်တာလဲ**

> add / remove မှာ fonts တွေကို remove လုပ်မိ ပြီးတော့ uninstall ပြီးတော့ install ပြန်လုပ်လည်း မ မြင်ရတော့ လို့

**အမှန်တကယ်ဘာဖြစ်သင့်တာလဲ**

uninstall ပြီးတော့ install ပြန်လုပ်ရင် ပြန် 
> တကယ်တန်းဘိုလိုဖြစ်သင့်တာလဲ

**Screenshots**

> screenshot နဲ့ပြလို့ရရင် ပြပေးပါ
![image](https://user-images.githubusercontent.com/38513484/143808723-84aed337-8da7-4550-8b80-1893c11e116d.png)

**အသုံးပြုနေသောအချက်အလက်များ**

- OS: [Windows 10 Pro] 

**အခြားအကြောင်းအရာ**

**Comment by thantthet** [comment]
https://github.com/thantthet/keymagic-keyboards ဒီမှာလိုချင်တဲ့ကီးဘုတ်ကို (.km2) ဆွဲပြီးပြန်သွင်းပါဗျာ
