### ISSUE TITLE
ကျနော် ‌keymegicဘောင်ထဲက font တွေဖျက်မိတယ်။ပြန်ထည့်ချင်တယ်

### ISSUE THREAD

**Issue by nyinchemco** [thantthet/keymagic#126]
**ပြဿနာကိုရေးပါ**

> ဘာဖြစ်တယ်ဆိုတာကို ရှင်းရှင်းလင်းလင်းရေးပေးပါ။

**ဘာလုပ်ရင်ဖြစ်တာလဲ**

> အောက်ပါအဆင့်များအတိုင်း လုပ်ရင်ဖြစ်ပါတယ် -

**အမှန်တကယ်ဘာဖြစ်သင့်တာလဲ**

> တကယ်တန်းဘိုလိုဖြစ်သင့်တာလဲ

**Screenshots**

> screenshot နဲ့ပြလို့ရရင် ပြပေးပါ

**အသုံးပြုနေသောအချက်အလက်များ**

- OS: [e.g. macOS, Windows 7, Windows 10]
- Version [e.g. 1.1]

**အခြားအကြောင်းအရာ**

> ပြဿနာနဲ့ဆိုင်တဲ့ အခြားအကြောင်းအရာများရှိလျှင်ရေးပါ

**Comment by Faiz-lord489** [comment]
excel font pyidaung suu font no typping [ # @

> 
![Capture](https://user-images.githubusercontent.com/103535260/163048492-0b2d1c3e-1ec0-416e-b861-256687ac2035.PNG)

**Comment by Faiz-lord489** [comment]
request to help me

**Comment by kokoye2007** [comment]
Please test with other fonts (eg Padauk)
It's not working ? It's keyboard error
If other fonts are working ? It's pyidaungsu font issues

**Comment by Zayarmoe** [comment]
I wrong delet my keyboard fornt

**Comment by kokoye2007** [comment]
> I wrong delet my keyboard fornt

Keyboard or Font 

### Keyboard
- https://keymagic.net/keyboards/
- https://github.com/thantthet/keymagic-keyboards

### Fonts
- https://github.com/AungMyoKyaw/Myanmar-Unicode-Fonts

---
- https://www.mmunicode.org/downloads/
