### ISSUE TITLE
Unable to install KeyMagic on Ventura

### ISSUE THREAD

**Issue by pmverma** [thantthet/keymagic#144]
**ပြဿနာကိုရေးပါ**

I installed keymagic as per https://keymagic.net/installation/macos/, but the guide is not updated for Ventura.
After installation, I was not able to find KeyMagic under Input Source as well.

**ဘာလုပ်ရင်ဖြစ်တာလဲ**

1. Install KeyMagic on macOS Ventura

**အမှန်တကယ်ဘာဖြစ်သင့်တာလဲ**

There should be a KeyMagic keyboard to select as an input method in Language settings.

**Screenshots**

> screenshot နဲ့ပြလို့ရရင် ပြပေးပါ

**အသုံးပြုနေသောအချက်အလက်များ**

- macOS Ventura Version 13.2.1
- MacBook 13-inch, 2019, Two Thunderbolt 3 ports

**အခြားအကြောင်းအရာ**

Please include a section for Ventura in the installation guide.

**Comment by phonezinoo** [comment]
Same happening here.

**Comment by thantthet** [comment]
KeyMagic is under **Multiple languages**. Please find it by typing into search box.

guide updated: https://keymagic.net/installation/macos/

<img width="827" alt="input-sources" src="https://github.com/thantthet/keymagic/assets/1355770/35a4ee67-0cc5-4cb9-91ce-bf797d195c63">

Thanks!
