### ISSUE TITLE
Any plan to update this project?

### ISSUE THREAD

**Issue by laicasaane** [thantthet/keymagic#26]
Do you have any plan to update this project? This tool is really helpful but there are features still missing: string index, match any. Also there is a bug on the `enter` key: type some words then press `enter`, then press `backspace`, the final word will be messed up.

I'm really fond of this project and want to help improving it. There are some features I want to add:
- Match any key. Currently, we can do matches on a set of characters. So, I want to have a similar set of keys, like:

```
$keys = VK_KEY_0 + VK_KEY_1 + VK_KEY_2 + ... + VK_KEY_9
$key[*] => '_'

// Combinations like `VK_SHIFT & VK_KEY_9` can also be used here.
```
- Range sets: `$range = ['0'-'9']` instead of `$range = '0123456789'`. This will have great effect on unicode sets like `$range = [U2000-U20FF]`.
- Exclude one or many characters from a set:

```
$range = [U2000-U20FF] - U2009
$exclude_more = $range - [U2030-U20EE]
```
- Using regex to do something like input reversing. For example, when the number `1560` is being typed, the latest digit will be placed at the start position of the segment, and the output will be `0651`. The rule for this job is

```
$digits = ['0'-'9']
(\b$digits[*]+) + $keys[*] => $digits[$2] + $1

// \b marks the beginning of a segment
// $digits[*]+ means "one or more of any character in the '0123456789' set"
// $1 refers to the whole (\b$digits[*]+) group
```
- Make rotating lists to reduce the number of rules that should be defined. That means, with a single line of code like `<VK_KEY_I> => {'ai', 'y', 'и', 'η'}`, we can press the `i` key 4 times to traverse through the strings in that list.

With these additional features, the keyboard layout could be more powerful with fewer line of codes.

However I'm not familiar with the codes and the mechanism of this tool. Can you help me understand, or point out a way for me to continue to work on this project?

**Comment by thantthet** [comment]
There is no plan to add new features for now. But I'll try my best effort to fix the bugs. :)

btw, there is already **Match any key** feature. What's the difference with existing feature?
Other features will be great to be added.

Sure, I can help you with the codes. It will be great to be contributed.

Please email me to: tªttkz.me

**Comment by Tyelpion** [comment]
I should explained more about `match any key`. First, we pretend that each `VK` is a symbol, I'll called it a `key symbol` to differentiate it from the `character symbol`s like 'a', '0', '#',... Then, those `key symbol`s can be concatenated to form a `string of keys`. This `string` can be assigned to a variable. Finally, we can apply `[*], [^], [1], [2],..., [$1], [$2],...` to that `string of keys`. Note that, any key combination using `&` operator (like `VK_SHIFT & VK_KEY_9`) is considered as a **single** symbol.

At this time, `VK` symbols aren't permitted to be assigned to a variable, and the `+` operator isn't permitted for the `VK`s on the RHS as well. It raises a syntax error here.


> there is already **Match any key** feature.

Do what you mean differ from what I mean by any chance? It's best if you provide a snippet to explain this feature.
