### ISSUE TITLE
Problem with Myansan Layout From KEYMAGIC Pre 2

### ISSUE THREAD

**Issue by htinkyaw85** [thantthet/keymagic#29]
Myansan layout has problem with ​​​ေ  (Ta Way Htoe) when used in Words 2010 with MYANMAR 3 Font.  It automatically changes to Myanmar Text every time.

In all other places in Windows 10 (notepad, file names, other places) are all OK. No problem with ​ေ .

In PowerPoint 2010, Fonts are far apart from each other.

**Comment by thantthet** [comment]
Thanks for report bro.

But font changing in Words or other program is not controlled by keymagic. Try upgrading your Microsoft Office.

Also font spacing is nothing to do with keymagic. For font spacing problem, you should report to font developer.
