### ISSUE TITLE
Ctrl+C/V/A doesn't work

### ISSUE THREAD

**Issue by htinkyaw85** [thantthet/keymagic#30]
When using Myanmar3std Layout, cannot type ငြေ 

Characters don't join together.  It happens in all places not only in Microsoft Office applications.  Most of Special Characters are also missing.
() - + *, etc.

All the universal shortcuts are also not working with KEYMAGIC like Ctr + C/V/A.  Those kinds of shortcuts work with any keyboards like Zawgyi or built-in windows keyboard (even though we r typing Myanmar Unicode Fonts), system understand those universal shortcuts.

**Comment by thantthet** [comment]
Thanks for feedback.

Note: Please open one issue for each problem. i open an new issue for Myanmar3 layout bug #31. I'll keep this issue only for Ctrl + C/V/A issue.

I can't reproduce the bug. I can copy/paste/select fine while keymagic open.
I suggest to try again and please comment back here.
