### ISSUE TITLE
Myanmar 3 layout bug

### ISSUE THREAD

**Issue by thantthet** [thantthet/keymagic#31]
When using Myanmar3std Layout, cannot type ငြေ

Characters don't join together. It happens in all places not only in Microsoft Office applications. Most of Special Characters are also missing.
() - + *, etc.

reported by @htinkyaw85

**Comment by htinkyaw85** [comment]
Hi bro Thant Thet,

Any update for the above bugs.  We r eagerly looking for new update.

Tks a lot
