### ISSUE TITLE
KeyMagic is not working in windows 10 x64

### ISSUE THREAD

**Issue by vinodvinu** [thantthet/keymagic#34]
Hi Team KeyMagic,
I have successfully installed KeyMagic in Windows 10 x64. But it is not showing my native language after i typed the hot key. None of the keyboards are working in KeyMagic. Is there any problem with win 10 64 bit ?

**Comment by thantthet** [comment]
It should be work but it needs dependencies to be installed correctly. We are working on get rid of requirement of dependencies. Meanwhile, you can try KeyMagic 2.0 Alpha here http://keymagic.net/download/keymagic-v2-0pre-2/ which requires no dependencies. Be sure to uninstall previous KeyMagic versions.

**Comment by vinodvinu** [comment]
Hi, 
Thanks for the update. It is working very nice in WIn10 64 bit. As it is a pre release, the lack of hot key assignment for each keyboard is the only issue. Rest is ok. Thanks once again.

**Comment by Theinkha** [comment]
I can't add other layout on keymagic, help me plz.

**Comment by vinodvinu** [comment]
@thantthet 
Now, KeyMagic pre release is not working in windows10 64 bit. It was wroked when installed, but after a restart something happened wrong. What to do ?

**Comment by Theinkha** [comment]
When I copy, it show " can't copy why registration keyboard".

**Comment by thantthet** [comment]
@vinodvinu Please tell me more about the error if any.

@Theinkha I think there is something wrong with your system, try to copy, paste the keyboard manually to keyboard folder, if you can't, this is not keymagic related issue.

**Comment by vinodvinu** [comment]
@thantthet ,
There is nothing more to say about the error. It simply not working now. If i a press a "A" key in keyboard, the letter "A" will appear in screen. I have my own km2 file. It is not working in keymagic2. And there is a few other keyboards layouts are coming with keymagic2 by default, those are not working now. I have uninstalled it and installed again. But no way, its not working.

**Comment by thantthet** [comment]
Do you have any anti-virus software installed?
