### ISSUE TITLE
Unable to add km2 file to Keymagic

### ISSUE THREAD

**Issue by mQn9x9ne** [thantthet/keymagic#35]
Hi

I downloaded and installed Keymagic 1.5.1 on Microsoft Windows 10 Home Edition (64-bit, US English). The default keyboard is US English. The installation was successful.

Next, I downloaded a file called [Tzerng_Koang.km2](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/tzerngkoang/Tzerng_Koang.km2)
However I was unable to add it to Keymagic. The error message was it already existed.

How do I solve the above issue?

**Comment by thantthet** [comment]
It means there's a keyboard file exists in keymagic layout folder with the same name. You should delete that file first.

**Comment by mQn9x9ne** [comment]
> It means there's a keyboard file exists in keymagic layout folder with the same name. You should delete that file first.

Firstly, I deleted all the keyboard files in Keymagic's layout folder.

Secondly, I tried to copy Tzerng_Koang.km2 file to that folder. The same error message appeared.

What is the fix?
