### ISSUE TITLE
What key "commits" in myansan?

### ISSUE THREAD

**Issue by kpfoley** [thantthet/keymagic#37]
the MyanSan smart input keyboard works well BUT the only key that "commits" is enter/return. Enter/return does other unwanted things, like submitting forms, etc.

On the older version, the space bar would commit. Now the space bar does not commit anymore. Can the space bar be restored as a "commit" key, or can another key (tab?) be used instead to commit?

I'm running latest keymagic on OS X Sierra.

**Comment by thantthet** [comment]
MyanSan keyboard is defined a rule for space key in its keyboard definition that prevents from committing the string. Currently there is no way to override the keyboard definition, for workaround you can use old version of MyanSan keyboard.

**Comment by kpfoley** [comment]
Thank you! What is the recommended way to commit a string with the new MyanSan keyboard? Right arrow?
