### ISSUE TITLE
how to type geometry 

### ISSUE THREAD

**Issue by pepemandalay** [thantthet/keymagic#42]
I'm using macOS sierra (10.12.5). I can't type geometry using myanmar3. The "Hta (ထ)" ekayar cannot use with Yayit. The characters appeared out of order (please see attached). 
![geometry](https://cloud.githubusercontent.com/assets/29152769/26745777/3e770faa-47ba-11e7-8c92-16f2fc979343.png)
Please advice. Thank you!

**Comment by thantthet** [comment]
please try to get better help in https://www.facebook.com/groups/mmUnicode
Since this is not keymagic issue itself. I will close this issue.
