### ISSUE TITLE
K-Editor shows an error report

### ISSUE THREAD

**Issue by vinodvinu** [thantthet/keymagic#44]
Hi there,
K-Editor shows an error report in my pc when i click on "Test" menu item. Here i am attaching the error daialogue image and a text file contains error message.
[K-Editor Error Report.txt](https://github.com/thantthet/keymagic/files/1150206/K-Editor.Error.Report.txt)
![captured_000157](https://user-images.githubusercontent.com/8840907/28238146-ee5e1b3a-696a-11e7-9735-c6665774c2e9.jpg)

**Comment by thantthet** [comment]
This usually due to dependency issue. Have you installed all dependencies linked at download page?

**Comment by vinodvinu** [comment]
Thanks and Problem solved.
