### ISSUE TITLE
Excel တွင် Keymagic သုံး၍ အဆင်မပြေခြင်း

### ISSUE THREAD

**Issue by kaungkyawswar** [thantthet/keymagic#47]
Windows 10, Office 2016 တွင် Keymagic  Myanmar3x/ မြန်စံ Layout , Pyidaungsu Font 2.1 သုံး၍ စာရိုက်ရာ Excel တွင် အောက်ပါအတိုင်းဖြစ်ပေါ်နေပါသည်။

- Num. Pad အသုံးပြု၍ မရခြင်း၊
- ပုံပါအတိုင်း တွေ့ရှိ, အကြောင်းအရာ, ဆွေးနွေးစသည့် စကားလုံးများအား ရိုက်ရာတွင် အမှန်မပေါ်ခြင်း(သဝေထိုး ရှေ့ရိုက်/နောက်ရိုက် စမ်းသပ်ပြီး)
![capture](https://user-images.githubusercontent.com/30788284/29010805-f158a85a-7b53-11e7-9bd5-0b185e19fb78.JPG)

**Comment by thantthet** [comment]
please test with latest version and reopen issue if it still exists.

**Comment by Mr-Zer0** [comment]
Latest Version ဆိုတာ Excel Latest Version ကို ပြောတာလား၊ Keymagic Latest Version ကို ပြောတာလားခင်ဗျ။
