### ISSUE TITLE
Doesn't work on Windows 10 64bit

### ISSUE THREAD

**Issue by kinhvanhoa** [thantthet/keymagic#48]
I've installed KeyMagic-v2.0Pre-4 on my computer (Windows 10 64 bit). 

It doesn't work at all. When I chose Myanmar 3x , it said "copying failed while registering keyboard!" 

How could I fix this problem? I am completely new to this Unicode keyboard. 

Please give me some advice. Thanks.

**Comment by thantthet** [comment]
This happens if the same file name already exists when adding new keyboard. The easiest way to workaround this issue is to rename keyboard file name other than myanmar3x.km2. After you renamed the keyboard file. You will be able to add into keymagic.

This issue will be fixed in next pre release.

**Comment by thantthet** [comment]
Fixed in [windows-2.0.0.5](https://github.com/thantthet/keymagic/releases/tag/windows-2.0.0.50)
