### ISSUE TITLE
HotKey settings doesn't work

### ISSUE THREAD

**Issue by mkpaul** [thantthet/keymagic#51]
HotKey stops working randomly. I am using Ctrl+3 for disabling/enabling and Ctrl + Q for choosing next keyboard as hot keys on windows 7. But randomly, hotkeys stops working, keymagic is still running, i can change the keyboard from system tray by right click. 

But right clicking on the system tray icon only allows enabling the keyboard. Subsequent click should disable the keyboard, in my view. It should be like a toggle switch.

**Comment by thantthet** [comment]
i hope this issue is resolved in keymagic 2
