### ISSUE TITLE
microsoft office 2016 has stop working with keymagic

### ISSUE THREAD

**Issue by ymyintw** [thantthet/keymagic#52]
Thanks.
It is very useful for me. I like it very much.
But it limits me in using Microsoft office 2016.
While typing Myanmar Unicode, it suddenly stopped the Microsoft word program. So sometimes I have no time to save my data. This occurs every time when I used it.

I send it with attached files. (This is just a sample.)

![20180717_150704](https://user-images.githubusercontent.com/41323459/42806594-cef68a44-89d4-11e8-8ccd-2f006fe0edcd.jpg)

While typing this  ... ... ... အဓိကစိန်ခေါ်မှုတစ်ရပ် ဖြ   then it stopped.
I try to type this word again and again, but the same error occur. I cannot type next word after these words. (အဓိကစိန်ခေါ်မှုတစ်ရပ် ဖြ )
Please see this attach file.
![20180717_150849](https://user-images.githubusercontent.com/41323459/42806633-e14d1640-89d4-11e8-80cb-a078e6b4c98a.jpg)

ဒါက နမူနာအဖြစ်အပျက်ပဲ ဖြစ်ပါတယ်။
စာရိုက်ရင် ရုတ်တရက် Microsoft word program က ရပ်သွားတတ်ပါတယ်။ (ဘယ်စာပဲ ရိုက်ရိုက် ဒီလိုမျိုး ခဏခဏ ဖြစ်ပါတယ်)
ဒါကြောင့် Window 10 မှာ built in ပါတဲ့ Burmese keyboard နဲ့ပြောင်းရိုက်တဲ့အခါ ဒီလို အဖြစ်အပျက်မျိုး တစ်ခါမှ မဖြစ်တော့ပါဘူး။
ဒါပေမယ့် Built in ပါတဲ့ keyboard က keymagic လောက် သုံးရတာ အဆင်မပြေပါဘူး။

note pad မှာ Keymagic နဲ့ ရိုက်တဲ့အခါ ဒီလို အဖြစ်အပျက် လုံးဝမဖြစ်ပါဘူး။
Microsoft word 2016 မှာပဲ ဖြစ်ပါတယ်။

*** တခြား computer Window 10 မှာပြောင်းရိုက်တဲ့အခါမှာလည်း ဒီ error အတူတူပဲ ဖြစ်ပါတယ်။

(keymagic 2.0 pre 4 ကိုသုံးပါတယ်)
(Windows 10 64 bits ဖြစ်ပါတယ်)

ေကျးဇူးတင်ပါတယ်။

**Comment by thantthet** [comment]
Thanks for reporting. Which keymagic keyboard layout are you using?

**Comment by ymyintw** [comment]
ဇတ်ကုဒ် - layout သုံးပါတယ်။

**Comment by thantthet** [comment]
ဒီမှာတော့ စမ်းကြည့်တာ ကောင်းနေတယ်ဗျ။ Windows 10 နဲ့ Office 2016 နဲ့ပဲ။ office version က 16.0.8625.2121 နဲ့စမ်းတာပါ။ အကို့ office version ဒီထက်နှိမ့်တာဆိုရင် office ကို update လုပ်ပြီးစမ်းကြည့်ပေးပါအကို

**Comment by ymyintw** [comment]
Office က latest version ပါ။
ျဖည္းျဖည္း႐ိုက္ရင္ မျဖစ္ပါဘူး။
Speed က 50 wpm ေက်ာ္သြားတဲ့အခါ ႐ုတ္တရက္ program ရပ္သြားတတ္တာပါ။

**Comment by ymyintw** [comment]
ရပါၿပီ။
ကြၽန္ေတာ့္ Laptop က memory ေၾကာင့္လို႔ ထင္ပါတယ္။
တျခား memory ျမင့္တဲ့ laptop နဲ႔အခု ျပန္သုံးၾကည့္ေတာ့ မျဖစ္ေတာ့ပါဘူး။
စိတ္႐ွည္႐ွည္နဲ႔ျပန္လည္ေျဖၾကားၿပီး ေျဖ႐ွင္းေပးလို႔ေက်းဇူးတင္ပါတယ္။
