### ISSUE TITLE
to add an option for individual setting

### ISSUE THREAD

**Issue by Knaung** [thantthet/keymagic#55]
Application တစ်ခုမှ တစ်ခုသို့ပြောင်းစဉ် Keyboard အလိုအလျောက်ပြန်ပြောင်းသော Option တစ်ခု ထည့်လျှင် ပိုအဆင်ပြေပါမည်။ ဥပမာ.. Notepad တွင် မြန်မာယူနီ သုံးနေပြီး Window explorer တွင် Ctrl+C, V, X များ သုံးမရခြင်း...

**Comment by thantthet** [comment]
1. please continue to track at #62 for first issue.
2. shortcut issue is fixed in 2.0.0.7

Please create separated issues for each problem for better following up.
