### ISSUE TITLE
Windows Key + Shortcuts Not working in KeyMagic 2.0.0.5

### ISSUE THREAD

**Issue by Heinlinhtun** [thantthet/keymagic#56]
When we try to use Windows Key + [] Shortcuts while we using Myanmar keyboard layouts, it's not working yet. For example I'm typing in Myanmar Keyboard Layout and trying to print screen with the shortcut Windows Key + PrtScn . It's not working. 
Please solve this issue.

**Comment by kokoye2007** [comment]
Keyman or Keymagic ?

https://github.com/thantthet/keymagic/wiki/List-of-Virtual-Key-Codes

**Comment by thantthet** [comment]
> Keyman or Keymagic ?
> 
> https://github.com/thantthet/keymagic/wiki/List-of-Virtual-Key-Codes

I think he meant keymagic 😃 I've edited the title.

**Comment by thantthet** [comment]
Fixed in https://github.com/thantthet/keymagic/releases/tag/windows-2.0.0.6
