### ISSUE TITLE
malware detected in 2.0.0.6 latest version

### ISSUE THREAD

**Issue by zabayin** [thantthet/keymagic#58]
Kaspersky Latest Version is Detected Keymagic 2.0.0.6 with following sir ...
Anyway i'm closed my anti-virus and updated. i'm trust you and thank you for keymagic.
hope you fix that on next release.
Regards,

Object Name
UDS:Trojan-Spy.Win32.Xegumumune

**Comment by thantthet** [comment]
Thanks for letting me know. It is a false positive. I've submitted to kaspersky for further analysis.

**Comment by zabayin** [comment]
Thank you sir :)

**Comment by thantthet** [comment]
The latest Kaspersky update is not detecting any more.
