### ISSUE TITLE
English only Numpad & Default Numpad

### ISSUE THREAD

**Issue by zabayin** [thantthet/keymagic#59]
Keymagic 2.0.0.6 မှာ unicode နဲ့ရိုက်နေရင်းနဲ့ Numpad ကို ရိုက်လိုက်ရင် မြန်မာလို ၁၂၃၄၅ မပေါ်ပဲနဲ့ အရင်လိုမျိုးပဲ 12345 ပေါ်ရင်ကောင်းမယ်ဗျာ .. ဘာလို့ဆို ခနခန key switch နေရတော့ Number တစ်လှည့် မြန်မာတစ်လှည့် ရိုက်တဲ့အခါမှာ အခက်အခဲတစ်ချို့ရှိပါတယ်ဗျ .. အများစုက မြန်မာစာသုံးပေမယ့်လည်း ကိန်းဂဏန်းကျရင် အင်္ဂလိပ်ဂဏန်းကိုသာ သုံးလို့ပါဗျ ... ပြောင်းပြောင်းနေရတော့ အဓိကကတော့ speed နှေးသွားလို့ပါဆရာ ... Thank you for your great app.

**Comment by thantthet** [comment]
ဘာကီးဘုတ်သုံးတာလဲ ထည့်ရေးပေးမှ ပြင်ပေးလို့ရမယ်ဗျ ပြည်ထောင်စု ဆိုရင်တော့ https://mcf.org.mm/contact-us.html ကို report လုပ်ပေးပါ။
