### ISSUE TITLE
‌ေဩာင်း ရေးလို့မရလို့

### ISSUE THREAD

**Issue by xfileammb** [thantthet/keymagic#60]
Office 2010, Office 2016 တွေမှာ ဆိုင်ရာဖောင့်ကို သုံးပြီးရေးကြည့်ပါတယ်။ ခုဒီနေရာမှာလည်း ‌ေဩာင်းရေးတာ အဆင်မပြေလို့ပါ။

**Comment by SnowFallGameStudio** [comment]
သိသလောက် ပြောရမယ်ဆိုရင် . . .

KeyMagic , Pyidaungsu MM (Keylayout) ကို မသုံးပါနဲ ပြသာနာတွေအများကြီးရှိပါတယ်။
 ‌စေ◌ျး (a +p +s +;) , ဈေး (a + Q + ;) နဲကိုလဲရေးလိုမရပါဘူး အသေးအသေးလေးတွေအများကြီးရှိပါတယ်။
သေ◌ြာင်း , ‌ေဩာင်း , သေ◌ြာ် , စေ◌ြာ် , စဥ◌် ,  သိသလောက် ရေးလိုမရတယ်ဟာတွေပါ။

KeyMagic , မြန်စံ (Smart) (Keylayout)
သြောင်း , သြောင်း , ဪ , စြော်, စျေး, စဥ် သုံးပြီးရေးထားပါ။ လက်ကွက် ဇယား မတူတော့ပါဘူး ကြည်ချင်ရင်တော့ 
https://www.facebook.com/485997864800090/photos/a.952580151475190/1399305156802685/?type=3&theater

Keyman ကိုပြောင်းသုံးပါအဆင်ပြေပါတယ်။
https://keyman.com/keyboards/sil_myanmar_my3 လက်ကွက် ဇယား 
https://help.keyman.com/keyboard/sil_myanmar_my3/1.5/sil_myanmar_my3.php
သြောင်း , သြောင်း , ဪ , စြော်, စျေး , စဥ်

အခြားအဆင်ပြေတာရှိလား မရှိလားတော့ဘူး မသိဘူး ကျွန်တော်က အခုကတော့ အဆင်ပြေပြေ စမ်းထားတယ်ဟာတွေပါ။

**Comment by thantthet** [comment]
ကီးဘုတ်နာမည်ပါမှ ဘာကီးဘုတ်မှာဖြစ်တာလဲဲဲဲဲဲသိမှ ပြင်ပေးလို့ရမယ်ဗျ။ ပြည်ထောင်စုသုံးနေတာဆိုရင်တော့ MCF ကထုတ်ထားတဲ့ကီးဘုတ်ဖြစ်တာကြောင့် MCF ကို  https://mcf.org.mm/contact-us.html report လုပ်ပေးပါ။ တခြား ကီးဘုတ်ဆိုရင်တော့ ဒီမှာ https://github.com/thantthet/keymagic-keyboards/issues ကီးဘုတ်နာမည်နဲ့ issue အသစ်ဖွင့်ပေးပါခဗျာ။
