### ISSUE TITLE
window 7 pro 64 bit ( DC client ) computer ပေါ်မှာ Keymagic ထဲက လက်ကွက်တွေ ပျောက်ကုန်တဲ့ issue

### ISSUE THREAD

**Issue by yanaungmyo** [thantthet/keymagic#61]
Window 7 professional 64 bit ကို  Domain Controller ရဲ့ Client အနေနဲ့ သုံးပြီး Keymagic v2.0.0.6 တင်ထားတယ် ... Computer restart ချပြီး ပြန်တတ်လာတာနဲ့   လက်ကွက်တွေ အကုန်ပြောက်ကုန်တယ် ... Network ထဲမှာရှိတယ့် Client တိုင်းတော့ မဖြစ်ဘူး .... တချို့ client computer တွေပဲဖြစ်နေတာ... 

Any one can help and figure out my issue?

**Comment by thantthet** [comment]
I don't know what domain controller is. But KeyMagic store its config file and keyboard files in `C:\Users\<username>\AppData\Roaming\KeyMagic` for each user. I think that is not compatible with DC?

**Comment by phyoewaipaing** [comment]
Hi Ko Yan Naung Myo,
Key magic ကို install လုပ်တဲ့ user account နဲ့   reboot ချပြီး ပြန်သုံးတဲ့ user profile မတူရင် လက်ကွက်တွေပြောက်ကုန်မှာပါ အဲ့ဒါကြောင့် install လုပ်တဲ့ user profile အောက်မှာရှိတဲ့ C:\Users\<username>\AppData\Roaming\KeyMagic  အောက်က json file ရယ် တခြား keyboard file အကုန်လုံးကို သုံးမဲ့ user ရဲ့လမ်းကြောင်းအောက်ကိုပြောင်းထည့်ပါ။ ဒါမှမဟုတ် GPO ကနေ file တွေကို ထည့်ပေးပါ။
