### ISSUE TITLE
Mac OS issue

### ISSUE THREAD

**Issue by RoxanneTay** [thantthet/keymagic#63]
Thank you for your great job done. But I was downloaded newest version on 1.5.3 but inside show me as 1.5.1 version. How come?

**Comment by thantthet** [comment]
You better remove/uninstall KeyMagic from the `Input Source` manually and do fresh install.

**Comment by RoxanneTay** [comment]
> You better remove/uninstall KeyMagic from the `Input Source` manually and do fresh install.

Sorry... How to check Input source and uninstall KeyMagic? Thanks

**Comment by RoxanneTay** [comment]
<img width="668" alt="Screen Shot 2019-09-23 at 9 25 05 PM" src="https://user-images.githubusercontent.com/25426030/65436853-cb388000-de48-11e9-8409-dc196b162cff.png">

**Comment by RoxanneTay** [comment]
I press the remove section and add them again they show like double icon.

**Comment by RoxanneTay** [comment]
I don't know how to uninstall.

**Comment by RoxanneTay** [comment]
![image](https://user-images.githubusercontent.com/25426030/65438253-2f5c4380-de4b-11e9-9ff4-8bb725bb8f0a.png)

**Comment by thantthet** [comment]
Try running this commands from terminal
```
rm -rf ~/Library/Input\ Methods/KeyMagic.app
sudo rm -rf /Library/Input\ Methods/KeyMagic.app
```

**Comment by RoxanneTay** [comment]
![image](https://user-images.githubusercontent.com/25426030/65439141-b5c55500-de4c-11e9-904a-8e46472347c2.png)

**Comment by RoxanneTay** [comment]
Is that all oK?

**Comment by thantthet** [comment]
All keymagic should be removed by now. Confirm that by looking in Input Sources.
You can reinstall keymagic after that.

**Comment by RoxanneTay** [comment]
![image](https://user-images.githubusercontent.com/25426030/65439340-0177fe80-de4d-11e9-9336-a5946c665fb7.png)
Yes no more in there. So I need to reinstall right?

**Comment by RoxanneTay** [comment]
![image](https://user-images.githubusercontent.com/25426030/65440582-f58d3c00-de4e-11e9-94ad-cb23e1567ab4.png)
Thank you so much. I am now on the lastest version of KeyMagic.
