### ISSUE TITLE
key magic မှာ keyboard တွေကို remove လုပ်ပြီး ဘယ်နေရာက km2 file တွေကို ပြန်ရွေးပေးရမှာလဲ?

### ISSUE THREAD

**Issue by toewailin** [thantthet/keymagic#64]
key magic မှာ keyboard တွေကို remove လုပ်ပြီး ဘယ်နေရာက km2 file တွေကို ပြန်ရွေး(add)ပေးရမှာလဲ?
window 10 x64 2018 edition.

**Comment by thantthet** [comment]
you can download from https://github.com/thantthet/keymagic-keyboards
