### ISSUE TITLE
ကျော် ပျော် at microsoft excel 2016

### ISSUE THREAD

**Issue by myominoo1982** [thantthet/keymagic#66]
window 10 license version, Microsoft excel 2016 crack version မှာ KeyMagic v2.0.0.7 နဲ့ (ကျော်) (ပျော်) စတဲ့ သဝေထိုးနဲ့ ယပင့် တွဲရေးလို့ မရဘူးဖြစ်နေတယ်။ word မှာတော့ ရတယ်။

**Comment by pphkp** [comment]
ဟုတ်တယ်ဗျ Office 2016 မှာ Word နဲ့ Power Point မှာ ချောချောမွေ့မွေ့ အဆင်ပြေတယ်။ ကျွန်တော် ဇော်ကုဒ်သုံးတာ။ Excel မှာ လပြည့် ရေးရင် ပြ့် လို့ထွက်တယ်။ 
--
