### ISSUE TITLE
Malware Detected

### ISSUE THREAD

**Issue by kozinthant** [thantthet/keymagic#68]
အရင်သုံးနေတဲ့ 2.0.0.6 မှာ ဘာပြဿနာမှ မရှိခဲ့ပါဘူး။ အခုအသစ်ထွက်တဲ့ Keymagic 2.0.0.7 ကို Install လုပ်တဲ့အချိန်မှာ Kaspersky Total Security 2019 က Malware ဆိုပြီး အကုန် ဖျက်ပစ်ပါတယ်။ Software ကိုလည်း သုံးလို့ မရဖြစ်နေပါတယ်။ အရင် 2.0.0.6 ကို ပြန်တင်သုံးတော့ အဆင်ပြေပါတယ်။ အရင် Keymagic 2.0Pre4 မှာလည်း တစ်ခါ အဲ့လို ဖြစ်ခဲ့ဖူးပါတယ်။

**Comment by thantthet** [comment]
This is Kaspersky bug. Already reported to Kaspersky for a fix.
