### ISSUE TITLE
ဦးရေးမရ keymagic တွင်

### ISSUE THREAD

**Issue by HeinZaw1133** [thantthet/keymagic#69]
ဦးရေးမရ ဦးရေးလျှင် ဥ◌ီးဟုပေါ်နေသည်

**Comment by thantthet** [comment]
this is keyboard related issue. keyboard related issues are to be reported at https://github.com/thantthet/keymagic-keyboards/issues

**Comment by myoheinapp** [comment]
Shift+U , Shift+D နဲ့ရေးလို့မရပါ Shift+M နဲ့ရေးရင်ရပါတယ်
