### ISSUE TITLE
keyboard 5 khu pyouk pyouk twer

### ISSUE THREAD

**Issue by mgzinthet13** [thantthet/keymagic#71]
plz help me, keymagic

**Comment by mgzinthet13** [comment]
Key magic ကို install လုပ္တဲ့ user account နဲ႔ reboot ခ်ၿပီး ျပန္သုံးတဲ့ user profile မတူရင္ လက္ကြက္ေတြေျပာက္ကုန္မွာပါ အဲ့ဒါေၾကာင့္ install လုပ္တဲ့ user profile ေအာက္မွာရွိတဲ့ C:\Users<username>\AppData\Roaming\KeyMagic ေအာက္က json file ရယ္ တျခား keyboard file အကုန္လုံးကို သုံးမဲ့ user ရဲ႕လမ္းေၾကာင္းေအာက္ကိုေျပာင္းထည့္ပါ။ ဒါမွမဟုတ္ GPO ကေန file ေတြကို ထည့္ေပးပါ။

**Comment by thantthet** [comment]
You may need run installer for each user.

**Comment by thantthet** [comment]
Solved in v2.0.1.0
