### ISSUE TITLE
Windows Shortcut Key (e.g. Wn+E, Wn+R) Stopped working When I enabled KeyMagic

### ISSUE THREAD

**Issue by aungthanlwin** [thantthet/keymagic#74]
Windows has some short cut keys. They are not working anymore when I enabled any KeyMagic Keyboard. E.g.  To open up run command box, you use Windows Key + R which is not working any more. 
https://turbofuture.com/computers/keyboard-shortcut-keys

**Comment by thantthet** [comment]
the latest version 2.0.0.9 has some improvements for hotkey issues. try the latest version and see if issue is resolved. You may please reopen this issue if problem persists.

**Comment by aungthanlwin** [comment]
The problem persists in current version. It happens in situation like when you're typing in Burmese and try to open My Computer by shortcut key (Wn+E) which no longer works but it will work if you switch to English keyboard.
