### ISSUE TITLE
Ubuntu ppa does not have a Release file 

### ISSUE THREAD

**Issue by cmn699** [thantthet/keymagic#75]
Unable to download Keymagic Ubuntu using the recommended Terminal commands because of the error E: The repository 'http://ppa.launchpad.net/ubuntu-mm/ppa/ubuntu eoan Eelease does not have a release file.

**Comment by thantthet** [comment]
@kokoye2007 လုပ်ပါအုံး :D

**Comment by kokoye2007** [comment]
https://launchpad.net/~kokoye2007/+archive/ubuntu/ppa/+copy-packages?field.name_filter=ibus-keymagic&field.status_filter=published&field.series_filter= 

![Screenshot from 2020-01-11 14-35-25](https://user-images.githubusercontent.com/3091754/72201172-b297b880-347f-11ea-860d-bf600c88e9b5.png)

**Comment by kokoye2007** [comment]
> Unable to download Keymagic Ubuntu using the recommended Terminal commands because of the error E: The repository 'http://ppa.launchpad.net/ubuntu-mm/ppa/ubuntu eoan Eelease does not have a release file.

Please use 
ppa:kokoye2007/ppa

**Comment by thantthet** [comment]
installation instructions updated at: https://keymagic.net/installation/linux/
