### ISSUE TITLE
Ctrl + Shift not working sometimes but interference some shortcuts

### ISSUE THREAD

**Issue by santoeaungdev** [thantthet/keymagic#76]
**Ctrl + Shift for Language on/off**
sometimes really work fine and even effect other program's shortcut (e.g. eclipse's open resource shortcut Ctrl+Shift+R and other Ctrl+Shift+.. related Key)
 
**Expection**
To be able to freely toggle Keyboard.
even on/off keybind is the same as other other program's shortcut, working fine.

.. ps. my fine definition is not the same as Singapore Fine.

Hope you can solve this bug as soon as possible.

**Comment by thantthet** [comment]
the latest version 2.0.0.9 has some improvements for hotkey issues. try the latest version and see if issue is resolved. You may please reopen this issue if problem persists.
