### ISSUE TITLE
hot key issue

### ISSUE THREAD

**Issue by MinChanSike** [thantthet/keymagic#78]
OS : Windows 10 _Version 10.0.18363 Build 18363_
KeyMagic: v2.0.0.7

Even disable **Next Keyboard** change hotkey, it's still working and 
Keyboard **enable/disable** hotkey is not work well, 
when I press `Shift + Ctrl`, **keymagic is off** message is showing all the time.
I has removed other keyboard layout.
My keymagic hotkey setting is below. Thanks for your effort.

![image](https://user-images.githubusercontent.com/2868221/72231058-26f36880-35f4-11ea-9287-ff968962c198.png)

**Comment by thantthet** [comment]
the latest version 2.0.0.9 has some improvements for hotkey issues. try the latest version and see if issue is resolved. You may please reopen this issue if problem persists.
