### ISSUE TITLE
KeyMagic Stopped Working

### ISSUE THREAD

**Issue by thantthet** [thantthet/keymagic#79]
**Describe the bug**
 KeyMagic stopped working when returning from `Ctrl`+`Alt`+`Delete` screen or certain system screen.

**To Reproduce**
1. Run KeyMagic
2. `Ctrl`+`Alt`+`Delete`
3. Return to Desktop
4. KeyMagic stopped working

**Expected behavior**
KeyMagic should be working

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.0.09

**Comment by thantthet** [comment]
solved in v2.0.1.0

**Comment by Vanic24** [comment]
Keyboard layout change to English even while typing with Myanmar layout and start freezing. If that happened, can only exit and reopen again but it taking longer time to open keymagic software even after it show in notification. Hope the update from developer...
