### ISSUE TITLE
not working on ARM 64-bit processor

### ISSUE THREAD

**Issue by suntungithub** [thantthet/keymagic#80]
**Describe the bug**
- Microsoft Surface pro x with processor ARM 64-bit
- Keymagic Windows version
Install လုပ်လို့ရပြီး, အသုံးပြုလို့မရဖြစ်နေတာပါ။ **32-bit (x86) versions** ဖြစ်မှရမယ်လို့ အဲဒီဆိုဒ်မှာ ‌တွေ့ရပါတယ်။ ဖြစ်နိုင်ရင် 32-bit (x86) versions လည်းထုတ်ပေး‌စေချင်ပါတယ်။ 
ref: https://mspoweruser.com/apps-that-will-not-work-on-microsoft-surface-pro-x/

**Comment by thantthet** [comment]
Please give a try for v2.0.1.0
