### ISSUE TITLE
kEditor 2 - kms cannot be compiled and saved

### ISSUE THREAD

**Issue by minkhaing-GitHub** [thantthet/keymagic#81]
Try using kEditor 2 for the first time which has just been compiled from the source. Have got "Parser program not found!" error.

Cannot test, compile nor save to a km2 file. Please let me know how to fix it. Thank you.

![kEditor2](https://user-images.githubusercontent.com/60225376/72994032-5d6d8680-3e31-11ea-997b-5b53e076e571.png)

**Comment by minkhaing-GitHub** [comment]
Hi Sir,

Parser source code has been found and compiled under cross-platform folder. Everything works fine after copying parser exe, ilk and pdb. Please help to close this case.

But I am not fully confident using my self compiled kEditor files. Could if be possible to share a download link to your latest kEditor Windows Installer please?

Thanks much :)

**Comment by thantthet** [comment]
sorry for the lake of documentation. kEditor itself doesn't have any documentation.
But if you are looking for kms scripting, please take a look at https://github.com/thantthet/keymagic/wiki/Guide-to-layout-scripting
