### ISSUE TITLE
Can't Install Kali

### ISSUE THREAD

**Issue by openjust** [thantthet/keymagic#82]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  ibus-keymagic-zgunicode
0 upgraded, 0 newly installed, 1 to remove and 781 not upgraded.
1 not fully installed or removed.
After this operation, 18.4 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 311283 files and directories currently installed.)
Removing ibus-keymagic-zgunicode (1.5.2) ...

**Comment by thantthet** [comment]
cannot help without providing more description of the issue. please write details as per issue template. You may reopen issue by providing more details.

**Comment by kokoye2007** [comment]
if you download ibus-keymagic-zgunicode only ?
pls install first ibus-keymagic

**Comment by kokoye2007** [comment]
download and install only ibus-keymagic-zgunicode ?
its not standalone package.
pls download and install first ibus-keymagic.
