### ISSUE TITLE
keymagic 1.5.5 for macOS can't be installed

### ISSUE THREAD

**Issue by myotheinoo** [thantthet/keymagic#83]
မနက် ၃ နာရီလောက်က keymagic version အသစ်တက်လာလို့ download လုပ်လိုက်ပါတယ်။ Download လုပ်ပြီးတော့ installation လုပ်လို့မရပါ။ Keymagic ကို input methods folder ထဲကို drag and drop မရပါဘူး။ အောက်က screen recording ထဲမှာသေသေချာချာ ရိုက်ပြထားပါတယ်
https://drive.google.com/file/d/1AdPGWBsHWpEXXl9lIlARjG9PbMzdmtKF/view?usp=sharing

macOS Catalina 10.15.2 ဖြစ်ပါတယ်။ ယခင်က keymagic မသွင်းထားဖူးပါ

**Comment by thantthet** [comment]
i'm not sure the cause of this but you can double click Input Methods and copy KeyMagic into that directory manually.

**Comment by myotheinoo** [comment]
Yes, I tried that too. When it comes to install, it happens nothing
https://drive.google.com/file/d/1laLwHzx20yPkrlKJUW2B72oH5gZclk57/view?usp=sharing

**Comment by thantthet** [comment]
issue verified and is having on some macos that doesnt allow to install and this release is deprecated.

**Comment by myotheinoo** [comment]
sadly, 1.5.4 package is also not able to install on Catalina.

**Comment by myotheinoo** [comment]
I have an update. Even though it happens nothing when you're trying to install, it actually installed quietly in the background. When you go to  > about this Mac > system report > application, then you're going to see keymagic app there already installed. And then there is a tricky way to find keymagic in the input sources. You will not see keymagic no matter how hard you find. You will have to manually type in keymagic in the search bar and voila keymagic will magically popup!

**Comment by thantthet** [comment]
that is standard installation steps. these instructions are written here https://keymagic.net/installation/macos/
