### ISSUE TITLE
Version 2.0.1.0 cannot be installed on Windows 10 Machine

### ISSUE THREAD

**Issue by kaungmyatlwin** [thantthet/keymagic#84]
**Describe the bug (ပြဿနာကိုရေးပါ)**
A clear and concise description of what the bug is. (ဘာဖြစ်တယ်ဆိုတာကို ရှင်းရှင်းလင်းလင်းရေးပေးပါ။)

**To Reproduce (ဘာလုပ်ရင်ဖြစ်တာလဲ)**
Steps to reproduce the behavior: (အောက်ပါအဆင့်များအတိုင်း လုပ်ရင်ဖြစ်ပါတယ် -)
1. Go to Downloads folder
2. Open Installer `KeyMagic-v2.0.1.0` (even with Administrator rights)
3. See error

**Expected behavior (ဖြစ်သင့်သော အခြေအနေ**)
The installer should open up right away.

**Screenshots**
![image](https://user-images.githubusercontent.com/11173080/74302380-322cd780-4d0b-11ea-80f2-4ff9587450cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 2.0.1.0

**Additional context**
Reverted back to version 2.0.0.9 helped solved the problem and Keymagic is working as expected.

**Comment by thantthet** [comment]
if you have antivirus running. You could try adding this installer file to exception.
