### ISSUE TITLE
Detected as Virus by Windows Defender

### ISSUE THREAD

**Issue by mml2020** [thantthet/keymagic#85]
![Key-Magic](https://user-images.githubusercontent.com/61011955/74434861-af825480-4e91-11ea-9dff-218a0d211d73.png)

Key Magic behavior is detected as suspicious by Microsoft Windows Defender.
Ppl - plz don't install in your PC.
To Admin Team - plz help to look at the source code and take necessary action to developer.

Thanks
Rgds
Maung

**Comment by thantthet** [comment]
Thanks for reporting but it usually is false detection.

I can assure that you can safely use it by adding it to exception but pls make sure to always download from https://github.com/thantthet/keymagic/releases
