### ISSUE TITLE
can't use sometimes 

### ISSUE THREAD

**Issue by htutaungwai25** [thantthet/keymagic#86]
can't change keyboard or enable or disable

**Comment by aungtunlinn1992** [comment]
I am also facing this issue on my window10. You can simply close and re-open your **keymagic** will temporarily solve this issue. 
_I am just a keymagic user._

**Comment by lwinmoethwin** [comment]
Also facing this issue and sometimes words are running like a keyboard error. but random words for each time.

**Comment by thantthet** [comment]
merged to #88
