### ISSUE TITLE
No MM font input

### ISSUE THREAD

**Issue by kghtet6** [thantthet/keymagic#88]
**Describe the bug (ပြဿနာကိုရေးပါ)**
A clear and concise description of what the bug is. (ဘာဖြစ်တယ်ဆိုတာကို ရှင်းရှင်းလင်းလင်းရေးပေးပါ။)
"Keychange happens, but no mm font input." 

**To Reproduce (ဘာလုပ်ရင်ဖြစ်တာလဲ)**
Steps to reproduce the behavior: (အောက်ပါအဆင့်များအတိုင်း လုပ်ရင်ဖြစ်ပါတယ် -)
1. Install the app.
2. Ctrl+Shift <<keychange>>
3. Type. 
4. Always English input in all keymagic keyboards.

**Expected behavior (ဖြစ်သင့်သော အခြေအနေ**)
"Myanmar font inputs."

**Screenshots**
"N/A"

**Desktop (please complete the following information):**
 - OS: Window 10 Pro 1909 November 2019 update
 - Browser: Microsoft Edge 
 - Version: 2018

**Additional context**

**Comment by thantthet** [comment]
*workaround for now,* quit the keymagic app and run again.

**Comment by mooezat** [comment]
(၁) Dota 2 ေဆာ့ရင္ keymagic န႔ဲၿငိေနတယ္ခင္ဗ် အဲ့ေတာ့ ပိတ္ၿပီးမွ ေဆာ့လို႔အဆင္ေျပတယ္။
(၂) အဲ့လိုပိတ္ၿပီးေဆာ့ၿပီးတဲ့အခါ စာ႐ိုက္ဖို ့keymagic  ကို ျပန္ဖြင့္ရင္ run ေတာ့ run တယ္ ဒါေပမဲ့ Font change လို ့မရဘူးခင္ဗ်။ ျမန္မာလို႐ိုက္ဖို႔ဘယ္လို ျပန္ေခၚေခၚမရတာ အဲ့ လိုျဖစ္တဲ့အခါ task manager မွာ end process လုပ္ၿပီး ျပန္ဖြင့္မွရတယ္။
ေက်းဇူးပါ။
