### ISSUE TITLE
This package is incompatible with this version of macOS.

### ISSUE THREAD

**Issue by khay** [thantthet/keymagic#90]
I am trying to install **keymagic-1.5.4.pkg** on macOS Catalina 10.15.3 (19D76) and the installer shows an error message; **This package is incompatible with this version of macOS.**

![Alt Text](https://i.ibb.co/5LkbN1L/Screenshot-2020-03-24-at-11-31-25-AM.png) #

**Comment by thantthet** [comment]
there is a bug in macos package installer. please do selection in **Destination** step (sometimes it needs a couple of tries to able to select **Destination**)

**Comment by htunwinlatt** [comment]
YES It Works ....Thanks
