### ISSUE TITLE
Key Magic is suddenly reported as a threat in Windows 10 PC

### ISSUE THREAD

**Issue by aungthanlwin** [thantthet/keymagic#92]
KeyMagic.exe is removed after the below message and can't reinstall the program from installer again.

![KeyMagic](https://user-images.githubusercontent.com/13598164/78455691-b0935f00-7654-11ea-97c0-9d1afc1874ed.PNG)

**Comment by thantthet** [comment]
thanks for reporting. this is false positive. you can help us reporting to Microsoft at https://www.microsoft.com/en-us/wdsi/filesubmission
