### ISSUE TITLE
Window security detects keymagic as trojan

### ISSUE THREAD

**Issue by picodechu** [thantthet/keymagic#93]
**Describe the bug (ပြဿနာကိုရေးပါ)**
Reinstallation doesn't work as it was received as a threat.

**To Reproduce (ဘာလုပ်ရင်ဖြစ်တာလဲ)**
အလကားနေရင်း ထဖြစ်သွားတာ

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10}
 - Browser [chrome]
![IMG_20200405_030957](https://user-images.githubusercontent.com/62974181/78460968-788b2b00-76eb-11ea-85e9-48d9eb7fb865.jpg)

**Comment by thantthet** [comment]
thanks for reporting. this is false positive. you can help us reporting to Microsoft at https://www.microsoft.com/en-us/wdsi/filesubmission
