### ISSUE TITLE
Artemis Virus is on your KeyMagic Program

### ISSUE THREAD

**Issue by eaglekoko** [thantthet/keymagic#94]
![image](https://user-images.githubusercontent.com/34076492/80072651-8b678180-856c-11ea-9073-dfcefd70e6c5.png)

**Comment by smilePyone** [comment]
The file C:\Program Files (x86)\KeyMagic\KeyMagic2.exe is infected with Trojan.GenericKD.33055476 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.
ဘာကြောင့် အဲလို ပြနေတာလဲ တော့ မသိဘူး ။

**Comment by eaglekoko** [comment]
Yes, System is clean.
Now I am using KeyMagic v2.0.0.7 that is no virus. Could you give me regenerate program file and send to me.
Thanks 
Ko Ko Gyi

**Comment by kokoye2007** [comment]
AutoIt လို့ခေါ်တဲ့  Virus ရေးရာမှာ အသုံးပြုတဲ့ Code နဲ့တူတာတွေ ပါလို့ပါ
MS ကိုတော့ Report တင်ထားထားတဲ့ Version တွေမှာ မဖြစ်တော့ပါဘူး။

https://www.microsoft.com/en-us/wdsi/filesubmission
