### ISSUE TITLE
Eastern Pwo Karen နှင့် Western Pwo Karen Keyboard တွေမှာ ကရင်စာလုံးများ မပါသေးခြင်း 

### ISSUE THREAD

**Issue by HtinLinHtut** [thantthet/keymagic#96]
ကျွန်တော် ကရင်ဖောင့် လက်ကွက်တွေ ဖြစ်တဲ့ အရှေ့ပိုးကရင် လက်ကွက်၊ အနောက်ပိုးကရင် လက်ကွက်၊ စကောကရင်လက်ကွက်တွေထဲမှာ သက်ဆိုင်ရာ ကရင် ဗျည်း၊ သရ၊ အသတ် စသည့် အက္ခရာများ ပါ/ မပါကို စစ်ဆေးကြည့်ခဲ့ပါတယ်။ 
အရှေ့ပိုး ကရင် လက်ကွက်မှာ
အရှေ့ပိုးကရင် သရ ဖြစ်တဲ့ 
Unicode 1034 က     ဴ  စာသင်္ကေတနှင့် 
အရှေ့ပိုးကရင် ထပ်ဆင့်ရေးတဲ့ စာလုံးတွေဖြစ်တဲ့ 
Unicode E05A က      စာသင်္ကေတ၊
Unicode 105E က    ၞ  စာသင်္ကေတ၊
Unicode 105F က    ၟ  စာသင်္ကေတနှင့်
Unicode E05C က      စာသင်္ကေတတွေဟာ လက်ကွက်မှာ မပါတာ တွေ့ရပါတယ်။
ဒါ့အပြင် ၆ ရဲ့ အပေါ်က    ဳ  စာသင်္ကေတဟာ အရှေ့ပိုး ကရင်စာမှာ အသုံးမရှိလို့ အရှေ့ပိုး ကရင်စာမှာ မပါသင့်ပါ။

အနောက်ပိုး ကရင် လက်ကွက်မှာ
အနောက်ပိုး ကရင် သရ ဖြစ်တဲ့
Unicode 1067 က  ၧ   စာသင်္ကေတ ကျန်နေပါတယ်။

စကောကရင် လက်ကွက်မှာတော့
စကောကရင် စာများ အားလုံးပါဝင်တာကြောင့် အကုန် အဆင်ပြေပါတယ်။

Myanmar Unicode Migration ရဲ့ Viber Phone ကိုလည်း ကျွန်တော် ရှာတွေ့ထားတဲ့ ကရင် ကီးဘုတ်မှာ တွေ့ရှိချက်တွေကို Photo Message ပေးပို့ထားပြီးပါပြီ ခင်ဗျာ။

သက်ဆိုင်ရာ ကီးဘုတ်တွေကို Update လုပ်ပြီးပါကလည်း အကြောင်းပြန်ပေးဖို့ မေတ္တာရပ်ခံပါတယ်။

ကျေးဇူးတင်စွာဖြင့်
ထင်လင်းထွဋ်
htinlin1278@gmail.com

**Comment by thantthet** [comment]
Thanks for reporting. ကရင်လက်ကွက်တွေက ဒီပရောဂျက်က ထုတ်ပေးထားတာမဟုတ်လို့ ပြင်ပေးလို့မရပါဘူးအကို။ ကီးဘုတ်ထုတ်သူကို တောင်းဆိုကြည့်ပါခဗျာ။
