### ISSUE TITLE
Keymagic has malicious codes?

### ISSUE THREAD

**Issue by theinhtitenyo** [thantthet/keymagic#97]
![image](https://user-images.githubusercontent.com/56152430/84619082-17a57d80-aefa-11ea-98b4-69b90aaad92d.png)

**Comment by kokoye2007** [comment]
၁) Keymagic Version
၂) OS Version
၃) Antivirus Version and Update


we need submit for Virus Scanning Report.

**Comment by kokoye2007** [comment]
1) Sophos AV
2) McAfee-GW
3) Cyren
4) SecureAge APEX

**Comment by theinhtitenyo** [comment]
> 
> 
> ၁) Keymagic Version
> ၂) OS Version
> ၃) Antivirus Version and Update
> 
> we need submit for Virus Scanning Report.

Hello Bro Ko Ko Ye,
I just scanned through virustotal.com, my OS version is window 10, keymagic version is 2.0.1.0.
Everything is in the screenshot bro.

**Comment by thantthet** [comment]
Hello,

No. it doesn't. Virus scanner always alert false positives.

I advise to use Kaspersky which reports clean.

**Comment by RAJUPROP** [comment]
Yes... Most of the Anti-Virus software identify KeyMagic v2.0.1.0 (Latest Version for WINDOWS) as Malware or Virus, incl. McAFEE, AVG, eScan, MalwareBytes, Norton, Sophos, and Avira AV.
